# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4df28d6f7ffba1875d4db4fde4e74cd9b84250f477a7eac1dad7cf9857788339ca37e1e4f34630eafe47e096b52793b37f1bc82c18594ca1ab92925bc753fc05

test:
  secret_key_base: 91ee55b998e7c654b98c48dc70daf1f116152a0e439f960814743c623a52887c6aab24c8eda836d80c9d3383deef12ff8e0b0665873022507e7bed2d9568ee91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
